---
title: "Principal Components Analysis"
---

\normalsize

```{r eval=FALSE, echo=indic_missings}
# Missing values imputation 
df <- imputeMissings::impute(df, method="randomForest")
```   

```{r eval=FALSE, echo=indic_missings}
# Define number of dimensions to keep in the results
ncp <- min(ncol(df),5)
# Perform PCA 
pca <-  PCA(df, ncp=ncp, scale.unit = scale)
```

```{r eval=FALSE, echo=indic_missings}
# Loadings 
## Center and scale 
df_svd <- scale(df, center=TRUE, scale=scale)
## SVD 
tmp <- svd.triplet(df_svd, ncp = ncp)
princomps <- tmp$V
colprincomp <- c("PC1", "PC2", "PC3", "PC4", "PC5")
rownames(princomps) <- colnames(df)
kable(princomps, digits=3, col.names=colprincomp[1:ncp], format="simple")
```   

```{r, results="asis", eval=eval_code}
cat("\\newpage ")
cat("\n# R Code License", fill=TRUE)
cat("In the report included R programming code, the \"Software\" is under the MIT license.")
cat("\\newline ")
cat("Copyright 2021 Denise Welsch")
cat("\\newline ")
cat("Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:")
cat("\\newline ")
cat("THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.")
```

  
```{r, results="asis", eval = eval_code}
cat("\n# References", fill=TRUE)
```
 

